"""
Opinion bank for the "Hot Takes" content type.

Same philosophy as caption_bank.py one level up: a fixed, hand-written pool cycled
deterministically via a committed index file, not generated per-run. No LLM call,
no runtime cost, no risk of a model quietly drifting off-brand over time.

DELIBERATELY GENERIC, not specific — read this before adding entries. An earlier
version referenced specific colors and materials ("Beige is boring", "That's a lot
of brass for one room"). The pipeline cycles through application photos with no
attribute awareness at all — it doesn't know or check what's actually IN a given
photo, so a line calling out "beige" can land on a moody dark room with no beige
anywhere in it, which reads as a visible mistake, not a stylistic choice. Every
entry here is an attitude or philosophy about design/home life in general, not a
claim about a specific color, material, or object — so it stays compatible with
whatever photo the rotation happens to land on. If adding new entries, apply the
same test: would this line still make sense over ANY of the 50 application photos,
not just the one you're picturing while writing it?
"""

OPINIONS = [
    ("They: It's just a house.", "Me: It is never just a house."),
    ("They: You're overthinking this room.", "Me: There is no such thing as overthinking a room."),
    ("They: A house is done when it's done.", "Me: A house is never done."),
    ("They: Nobody notices the details.", "Me: I notice everything."),
    ("They: You've redone this room three times.", "Me: And I'll do it again."),
    ("They: It's just a corner of a room.", "Me: There are no small corners."),
    ("They: That took way too long to get right.", "Me: Correct amount of time."),
    ("They: You could have just left it alone.", "Me: I could have. I didn't."),
    ("They: Most people wouldn't spend this much time on a room.", "Me: I am not most people."),
    ("They: It looked fine before.", "Me: Fine is not the goal."),
    ("They: You're never satisfied.", "Me: Correct."),
    ("They: This is a lot of effort for one room.", "Me: This is the appropriate amount of effort."),
    ("They: Just buy whatever's on sale.", "Me: Absolutely not."),
    ("They: A space is just a space.", "Me: A space is a mood."),
    ("They: You should be done decorating by now.", "Me: I will never be done."),
    ("They: Nobody else will notice this changed.", "Me: I will notice."),
    ("They: This room already looks good.", "Me: Good is not the same as right."),
    ("They: You spend too much time on this.", "Me: I spend exactly enough time on this."),
    ("They: It's just decor.", "Me: It is never just decor."),
    ("They: You can't tell the difference.", "Me: I can always tell the difference."),
    ("They: This is excessive.", "Me: This is thorough."),
    ("They: Just live with it as it is.", "Me: I will not."),
    ("They: A room doesn't need a personality.", "Me: Every room needs a personality."),
    ("They: You'll change your mind about this in a year.", "Me: Probably. I'll deal with it then."),
    ("They: This wasn't necessary.", "Me: It was necessary to me."),
    ("Nobody asked for my opinion on this room.", "I gave it anyway."),
    ("There is a right way to do this and a done way.", "I only do the right way."),
    ("Some people redecorate. I renovate the same room forever.", "Same thing, more expensive."),
    ("A room can be finished.", "This one is not allowed to be."),
    ("They said pick a lane.", "I picked all of them."),
    ("Good enough is a trap.", "I have never fallen for it."),
    ("This room took three tries.", "It will take a fourth."),
    ("They: You're going to redo this again, aren't you.", "Me: Already have."),
    ("A house says a lot about a person.", "Mine says I don't stop."),
    ("There's such a thing as too much detail.", "I have never found it."),
    ("They: Just pick something and move on.", "Me: I did. I moved on to fixing it more."),
    ("Some rooms are a phase.", "Mine are a project."),
    ("They: You've spent more time on this than the room is worth.", "Me: The room is worth exactly this much time."),
    ("A finished room is a myth.", "I have never seen one."),
    ("I don't do compromises.", "I do reconsiderations."),
    ("They: You'll move on to the next room eventually.", "Me: Eventually is doing a lot of work in that sentence."),
    ("This room is not a mistake.", "It is a draft."),
    ("They: You already redid this once.", "Me: Once is a starting point, not a finish line."),
    ("Perfect is unreachable.", "That has never once stopped me from reaching."),
    ("They: You already have enough furniture.", "Me: I have enough furniture for the room I have. Not the room I'm becoming."),
    ("They: This is just a phase.", "Me: This phase has lasted three years."),
    ("They: Can you relax about the house for one day?", "Me: I relaxed yesterday. Look where that got us."),
    ("They: You don't need to fix what isn't broken.", "Me: I don't fix what's broken. I fix what's almost right."),
    ("They: It's 11pm, stop rearranging.", "Me: The room doesn't know what time it is."),
    ("They: This isn't a showroom.", "Me: Not yet."),
    ("They: You said this was the final version.", "Me: I lied."),
    ("They: Just enjoy the room instead of tweaking it.", "Me: This is how I enjoy it."),
    ("They: You're going to move that again?", "Me: It knows what it did."),
    ("They: Other people don't do this.", "Me: Other people's rooms show it."),
    ("They: You can't please everyone with this room.", "Me: I'm not trying to please everyone. I'm trying to please the room."),
    ("They: This room already has a theme.", "Me: Themes evolve."),
    ("They: You keep starting over.", "Me: I keep getting closer."),
    ("They: It's not that deep.", "Me: It's exactly that deep."),
    ("They: You'll never be satisfied.", "Me: Satisfaction was never the plan."),
    ("They: This project has no end date.", "Me: Correct."),
    ("They: You have a vision problem.", "Me: I have a vision. That's not a problem."),
    ("They: The room was fine an hour ago.", "Me: An hour is a long time."),
    ("They: You keep changing your mind.", "Me: I keep changing the room's mind."),
    ("They: This isn't your full-time job.", "Me: It is now."),
    ("They: You can stop any time.", "Me: I know. I choose not to."),
    ("They: Nobody's grading this room.", "Me: I am. Constantly."),
    ("They: You already redid the whole thing once.", "Me: Practice run."),
    ("They: This room doesn't need more work.", "Me: Every room needs more work. Some just hide it better."),
    ("They: You're chasing perfect.", "Me: I'm chasing correct. Perfect is a bonus."),
    ("A room can lie to you.", "Mine isn't allowed to."),
    ("Some people decorate to fill space.", "I decorate to make a point."),
    ("A house doesn't ask to be finished.", "I finish it anyway. Then I start over."),
    ("There's a version of this room that's good enough.", "I have never met her."),
    ("Comfort is fine.", "Correct is better."),
    ("I don't get attached to furniture.", "I get attached to what it's supposed to become."),
    ("This room isn't for guests.", "It's for me proving a point to myself."),
    ("A budget is a suggestion.", "I don't take suggestions well."),
    ("They said this room would never be perfect.", "They were right. I kept going anyway."),
    ("Some people call it obsessive.", "I call it paying attention."),
    ("This room has seen four versions of me.", "It's getting a fifth."),
    ("I don't decorate for other people.", "I decorate so other people finally understand."),
    ("Nothing in this room is an accident.", "Except the one thing I haven't fixed yet."),
    ("A room reflects the person who made it.", "Mine reflects the person I'm trying to become."),
    ("They: You'll regret spending this much time on it.", "Me: I regret nothing. Yet."),
    ("They: You're not a professional.", "Me: Not yet."),
    ("They: This is a hobby.", "Me: This is a calling."),
    ("They: The room isn't going anywhere.", "Me: Neither am I."),
    ("They: You keep adding things.", "Me: I keep adding the right things. Eventually."),
    ("They: You'll never top the last version.", "Me: Watch me."),
    ("They: Just copy what you saw online.", "Me: I don't copy. I correct."),
    ("They: This room is already better than most.", "Me: Most is not the bar."),
    ("They: You've been 'almost done' for a year.", "Me: Almost is doing a lot of work in that sentence. So am I."),
    ("They: You keep making this harder than it needs to be.", "Me: I keep making it as hard as it deserves."),
    ("They: Just trust your first instinct.", "Me: My first instinct was wrong. So was my second."),
]
