"""
Asset prep for the transformation-reel format (a NEW, standalone content type --
see llms.txt. Not the c/d swatch+application series, not the e-series montage
format; this one is "derelict room becomes a finished luxury room, human workers
mid-transformation" and it needs three images of the SAME architectural space,
not a swatch/application pair).

Generates, for one concept: a "before" (derelict/beat-down), a "mid" (workers
actively renovating), and an "after" (finished, high-end, styled) image of one
room. All three are generated with gemini-2.5-flash-image on Vertex AI -- the
model this project already confirmed working end-to-end for the e-series (see
llms.txt "Vertex AI image generation: confirmed working end-to-end"), not BFL
FLUX (that's the c/d-series' own tool, concept_tools/generate_concept.py, and
stays untouched here).

Chained generation, not three independent prompts: "after" is generated first
from a text description, then "before" and "mid" are each generated by handing
the model the "after" image alongside an edit instruction (gemini-2.5-flash-image
takes an image directly in `contents` alongside text -- see llms.txt for the
confirmed contents=[prompt, PIL.Image] pattern). This is the same reason
concept_tools/edit_room.py hands FLUX an input_image instead of re-rolling from
scratch: architecture, camera angle and framing have to MATCH across all three
frames for Veo's first/last-frame conditioning to read as one continuous space
rather than three different rooms. A fresh independent generation for each state
would not guarantee that; editing the same source image forward does.

Usage: python transformation_reel/generate_concept_frames.py <concept_id> <out_dir>
Writes <out_dir>/<concept_id>_after.png, _mid.png, _before.png.
"""
import sys
from io import BytesIO
from pathlib import Path

from google import genai
from PIL import Image

PROJECT = "project-58f4f689-36b9-406b-bfa"
LOCATION = "us-central1"
MODEL = "gemini-2.5-flash-image"

# Shared across every concept in this series, same "affirmative, no negatives"
# discipline the d-series prompts use (see llms.txt BFL prompting rules) --
# it's good practice for any generative image model, not a FLUX-specific quirk.
SPATIAL_RULE = (
    "The room is a coherent, physically real 3D space: every piece of furniture "
    "is fully separated from every other by visible floor or wall, all legs and "
    "bases are complete and resting on the floor, and any doorway or walking "
    "route is left clear and passable."
)


def generate_after(client, concept):
    prompt = (
        f"A photorealistic interior photograph of {concept['room']}, styled in "
        f"{concept['style']}. Materials clearly visible: {concept['materials']}. "
        f"Warm 2700K lamplight at several heights against cool light from the "
        f"windows, shadows holding real detail, no blown highlights, no hard sun "
        f"shafts. Eye-level three-quarter view, real depth with objects in the "
        f"near field. {SPATIAL_RULE} Fully furnished, finished, high-end, "
        f"magazine-quality real estate photography, vertical 9:16 composition, "
        f"no text, no watermark, no people."
    )
    print("--- generating AFTER ---")
    response = client.models.generate_content(model=MODEL, contents=[prompt])
    return _first_image(response)


def generate_before(client, concept, after_image):
    prompt = (
        "Show this exact same room, same camera angle, same architecture, same "
        "windows and doorways -- but stripped down to a derelict, unfinished "
        "construction state: bare subfloor or cracked original flooring, patchy "
        "plaster and peeling old paint on the walls, no furniture, no styling, "
        "exposed conduit or wiring in one place, dust sheets, a single bare "
        "work-light or harsh fluorescent tube instead of the finished lighting. "
        f"{SPATIAL_RULE} No people. No text. Keep the room's proportions, "
        "windows and doorway positions identical to the reference image."
    )
    print("--- generating BEFORE (edited from AFTER) ---")
    response = client.models.generate_content(model=MODEL, contents=[prompt, after_image])
    return _first_image(response)


def generate_mid(client, concept, before_image, after_image):
    prompt = (
        "Show this exact same room, same camera angle, same architecture, "
        "windows and doorways as both reference images -- but mid-renovation, "
        "roughly halfway between the derelict first reference and the finished "
        "second reference. Two or three human tradespeople actively working: one "
        "painting a wall with a roller, one installing flooring or trim, one "
        "carrying or positioning a piece of furniture. Visible tools, a ladder or "
        "light scaffolding, some materials staged in the room, partial "
        "furnishing -- not empty, not finished. Natural work-in-progress mess: "
        "drop cloths, an open tool bag, offcuts. "
        f"{SPATIAL_RULE} No text. Keep proportions, windows and doorway "
        "positions identical to both reference images."
    )
    print("--- generating MID (edited from BEFORE + AFTER) ---")
    response = client.models.generate_content(
        model=MODEL, contents=[prompt, before_image, after_image]
    )
    return _first_image(response)


def _first_image(response):
    for candidate in response.candidates:
        for part in candidate.content.parts:
            inline = getattr(part, "inline_data", None)
            if inline and getattr(inline, "data", None):
                return Image.open(BytesIO(inline.data))
    raise RuntimeError(f"No inline image data in response: {response!r}"[:1000])


CONCEPTS = {
    "t01": {
        "room": "a living room with a large window wall and a fireplace",
        "style": "warm modern minimalism",
        "materials": "white oak flooring, honed limestone fireplace surround, "
        "linen upholstery, brushed brass fixtures",
    },
}


def main():
    if len(sys.argv) != 3:
        print("Usage: generate_concept_frames.py <concept_id> <out_dir>")
        raise SystemExit(1)
    concept_id, out_dir = sys.argv[1], Path(sys.argv[2])
    concept = CONCEPTS[concept_id]
    out_dir.mkdir(parents=True, exist_ok=True)

    client = genai.Client(vertexai=True, project=PROJECT, location=LOCATION)

    after_img = generate_after(client, concept)
    after_img.save(out_dir / f"{concept_id}_after.png")
    print(f"Saved {out_dir / f'{concept_id}_after.png'}")

    before_img = generate_before(client, concept, after_img)
    before_img.save(out_dir / f"{concept_id}_before.png")
    print(f"Saved {out_dir / f'{concept_id}_before.png'}")

    mid_img = generate_mid(client, concept, before_img, after_img)
    mid_img.save(out_dir / f"{concept_id}_mid.png")
    print(f"Saved {out_dir / f'{concept_id}_mid.png'}")


if __name__ == "__main__":
    main()
